export type Locale = 'zh-CN' | 'en-US';

export const content = {
  'zh-CN': {
    nav: {
      home: '首页',
      catalog: '商店',
      product: '示例产品',
      service: '示例服务',
    },
    common: {
      loading: '正在加载树懒云数据...',
      error: '加载失败',
      backToCatalog: '返回商店',
      sourceMode: '数据来源',
      mock: '原型数据',
      live: 'Paymenter 实时数据',
      startingFrom: '起',
      theme: '主题',
      language: '语言',
      notAvailable: '暂不可用',
    },
    home: {
      kicker: '专业 VPS 服务商客户端原型',
      title: '用独立品牌前端，接住 Paymenter 的能力上限',
      subtitle: '树懒云把商品、服务、状态和购买路径重新设计成更专业、更清爽、更像成熟 VPS 服务商的体验。',
      primaryCta: '进入商店',
      secondaryCta: '查看示例服务',
      featuredTitle: '推荐实例',
      featuredSubtitle: '为一期开场页面准备的重点产品卡片。',
      categoryTitle: '产品分类',
      categorySubtitle: '先把目录与信息架构建立起来，后续再逐步接真实库存与可用区。',
    },
    catalog: {
      title: '商店与分类',
      subtitle: '以树懒云自己的目录结构承接 Paymenter 商品，不再依赖上游主题页面。',
      allProducts: '全部产品',
    },
    product: {
      title: '产品详情',
      plans: '计费方案',
      config: '购买配置',
      features: '核心特性',
      notes: '购买说明',
      summary: '订单摘要',
      choosePlan: '选择方案',
      noConfig: '当前数据源尚未提供真实配置项，一期先保留结构与提示。',
      provisionalAction: '下单动作将在二期接入',
    },
    service: {
      title: '客户服务详情',
      details: '服务详情',
      properties: '服务属性',
      network: '网络信息',
      actions: '操作区',
    },
    status: {
      active: '运行中',
      pending: '待开通',
      suspended: '已暂停',
      cancelled: '已取消',
      unknown: '未知',
    },
  },
  'en-US': {
    nav: {
      home: 'Home',
      catalog: 'Store',
      product: 'Sample Product',
      service: 'Sample Service',
    },
    common: {
      loading: 'Loading Sloth Cloud data...',
      error: 'Request failed',
      backToCatalog: 'Back to store',
      sourceMode: 'Data source',
      mock: 'Prototype data',
      live: 'Live Paymenter data',
      startingFrom: 'from',
      theme: 'Theme',
      language: 'Language',
      notAvailable: 'Unavailable for now',
    },
    home: {
      kicker: 'A premium VPS client prototype',
      title: 'A branded frontend that scales beyond default billing themes',
      subtitle: 'Sloth Cloud reshapes products, services, status views, and purchase flows into a cleaner VPS customer experience.',
      primaryCta: 'Browse store',
      secondaryCta: 'Open sample service',
      featuredTitle: 'Featured instances',
      featuredSubtitle: 'Hero products for the phase-one showcase.',
      categoryTitle: 'Categories',
      categorySubtitle: 'We are establishing a durable information architecture before deeper live integrations.',
    },
    catalog: {
      title: 'Store and categories',
      subtitle: 'Sloth Cloud owns the storefront experience while Paymenter stays behind the BFF.',
      allProducts: 'All products',
    },
    product: {
      title: 'Product detail',
      plans: 'Billing plans',
      config: 'Purchase configuration',
      features: 'Highlights',
      notes: 'Purchase notes',
      summary: 'Order summary',
      choosePlan: 'Choose a plan',
      noConfig: 'The current data source does not expose real config options yet, so the structure stays in place for phase one.',
      provisionalAction: 'Ordering will be connected in phase two',
    },
    service: {
      title: 'Client service detail',
      details: 'Service detail',
      properties: 'Service properties',
      network: 'Network',
      actions: 'Actions',
    },
    status: {
      active: 'Active',
      pending: 'Pending',
      suspended: 'Suspended',
      cancelled: 'Cancelled',
      unknown: 'Unknown',
    },
  },
} as const;

