export type Locale = 'zh-CN' | 'en-US';

export const content = {
  'zh-CN': {
    nav: {
      home: '首页',
      catalog: '商店',
      login: '登录',
      register: '注册',
      account: '控制台',
      logout: '退出',
    },
    common: {
      loading: '正在加载树懒云数据...',
      error: '请求失败',
      backToCatalog: '返回商店',
      sourceMode: '数据来源',
      mock: '演示模式',
      live: '真实数据',
      themeDark: '黑暗',
      themeLight: '明亮',
      languageZh: '中文',
      languageEn: 'EN',
      empty: '暂无可展示内容',
      loginRequired: '登录后继续',
      hello: '你好',
      accountReady: '认证已完成',
    },
    home: {
      kicker: '树懒云 Headless 客户端',
      title: '更像专业 VPS 服务商，而不是默认面板',
      subtitle: '前台体验、商品展示和用户认证都由我们自己的 Web 与 BFF 接管，Paymenter 退到后方做计费引擎。',
      primaryCta: '进入商店',
      secondaryCta: '立即登录',
      featuredTitle: '真实商品',
      featuredSubtitle: '以下内容来自新的 Headless catalog 接口。',
      categoryTitle: '真实分类',
      categorySubtitle: '分类、商品与价格卡片都不再依赖旧的 Livewire 页面。',
    },
    catalog: {
      title: '商店 / 分类',
      subtitle: '按分类浏览真实商品，价格、周期与基础配置都来自 Paymenter Headless API。',
      allProducts: '全部商品',
      stock: '库存',
      noProducts: '当前分类下还没有可售商品。',
    },
    product: {
      summary: '购买概览',
      plans: '计费周期',
      config: '购买配置',
      os: '操作系统',
      details: '商品详情',
      loginHint: '登录后即可继续接入下单链路。',
      configEmpty: '该商品目前没有额外配置项。',
      checkoutPending: '结算 API 下一步接入，这一版先完成真实商品与真实认证。',
    },
    auth: {
      loginTitle: '登录树懒云',
      loginSubtitle: '使用 Paymenter Headless Auth API 获取真实访问凭证。',
      registerTitle: '注册树懒云',
      registerSubtitle: '新用户创建成功后，将直接获得可用访问令牌。',
      email: '邮箱',
      password: '密码',
      code: '二步验证码',
      firstName: '名字',
      lastName: '姓氏',
      passwordConfirmation: '确认密码',
      submitLogin: '登录',
      submitRegister: '创建账号',
      tfaHint: '检测到两步验证，请补充验证码后再次提交。',
      alreadyHaveAccount: '已有账号？去登录',
      needAccount: '还没有账号？去注册',
    },
  },
  'en-US': {
    nav: {
      home: 'Home',
      catalog: 'Store',
      login: 'Login',
      register: 'Register',
      account: 'Console',
      logout: 'Logout',
    },
    common: {
      loading: 'Loading Sloth Cloud data...',
      error: 'Request failed',
      backToCatalog: 'Back to store',
      sourceMode: 'Data source',
      mock: 'Demo mode',
      live: 'Live data',
      themeDark: 'Dark',
      themeLight: 'Light',
      languageZh: '中文',
      languageEn: 'EN',
      empty: 'Nothing to show yet',
      loginRequired: 'Continue with login',
      hello: 'Hello',
      accountReady: 'Authenticated',
    },
    home: {
      kicker: 'Sloth Cloud headless client',
      title: 'Built like a premium VPS storefront, not a default panel skin',
      subtitle: 'The branded web app and BFF now own catalog delivery and user auth while Paymenter stays behind the edge.',
      primaryCta: 'Browse store',
      secondaryCta: 'Sign in',
      featuredTitle: 'Live products',
      featuredSubtitle: 'These cards are rendered from the new headless catalog endpoints.',
      categoryTitle: 'Live categories',
      categorySubtitle: 'Categories, products, and prices are no longer tied to the old Livewire frontend.',
    },
    catalog: {
      title: 'Store / Categories',
      subtitle: 'Browse real products by category, backed by the new Paymenter headless API.',
      allProducts: 'All products',
      stock: 'Stock',
      noProducts: 'No products are available in this category yet.',
    },
    product: {
      summary: 'Configuration summary',
      plans: 'Billing plans',
      config: 'Configuration',
      os: 'Operating systems',
      details: 'Product detail',
      loginHint: 'Sign in first to continue into the order flow.',
      configEmpty: 'This product currently has no extra config options.',
      checkoutPending: 'Checkout is the next API slice. This release focuses on live auth and live catalog data.',
    },
    auth: {
      loginTitle: 'Sign in to Sloth Cloud',
      loginSubtitle: 'Use the Paymenter headless auth API to get a real access token.',
      registerTitle: 'Create your Sloth Cloud account',
      registerSubtitle: 'Successful registration returns a live token immediately.',
      email: 'Email',
      password: 'Password',
      code: 'Two-factor code',
      firstName: 'First name',
      lastName: 'Last name',
      passwordConfirmation: 'Confirm password',
      submitLogin: 'Sign in',
      submitRegister: 'Create account',
      tfaHint: 'Two-factor authentication is enabled. Enter your code and submit again.',
      alreadyHaveAccount: 'Already have an account? Sign in',
      needAccount: 'Need an account? Register',
    },
  },
} as const;
